#!/usr/bin/perl

# Pass in a URL to a story/comment/user/subreddit, and it displays the exact date/time that the
# story/comment/etc was created.

    use strict;
    use warnings;

    use LWP::Simple;
    use JSON::XS;
    use Data::Dumper;

    # see http://www.reddit.com/dev/api#fullnames
    my %type_prefixes = (
        t1 => 'comment',
        t2 => 'account',
        t3 => 'story',      # officially called a "link", I prefer "story", since it's a link + comments
        t4 => 'message',
        t5 => 'subreddit',
        t6 => 'award',
        t8 => 'promo campaign',
    );

    # for DEVELOPMENT PURPOSES only -- should be commented out normally
    #@ARGV = 'http://www.reddit.com/r/blog/comments/1osafg/thanks_for_the_gold/'  unless @ARGV;

my $json_url = shift
    or die "Specify the URL of a story/comment/user/subreddit\n";


# If this is a subreddit, then get the subreddit's metadata.  If we didn't append "/about", then
# we would get a list of posts, which isn't what we want.
if ($json_url =~ m#reddit\.com/r/[^/]*/?$#i) {
    $json_url =~ s#/?$#/about/.json#;
}

# append ".json" if it isn't already there
$json_url =~ s#(/(\.json)?)?$#/.json#i;
print "Fetching $json_url\n\n";

my $json = get $json_url
    or die "Unable to fetch that URL\n";

$json = decode_json $json;
        # die Dumper $json;

    # To debug this info, run something like this:
    #       curl http://www.reddit.com/r/blog/comments/1osafg/thanks_for_the_gold/.json | pretty -j -
    # That *should* be the exact same data, though it's possible it isn't.
    # That uses this utility:  https://github.com/DeeNewcum/dotfiles/blob/master/bin/pretty

#my %kinds = (
#    t3 => 'comment or story',
#);

$json = $json->[0]      if (ref($json) eq 'ARRAY');

my $kind = $json->{kind};

if ($kind eq 'Listing') {
    $json = $json->{data}{children}[0];
}

   $kind    = $json->{kind};
my $created = $json->{data}{created_utc};
            #die Dumper [$kind, $created];

print "This $type_prefixes{$kind} was created on:\n\t",
        scalar(gmtime($created)), "\n";


