#!/bin/bash

# find comments where the poster is talking about trans* issues

./grep_comments.pl "$1" -b '(?i)\b((?!=transportation|transmission|transcript|translat|transparen|transform|transfer|transpired)trans\S*|cis|cisgender)\b' | less
