#!/bin/bash

# find comments where the poster is talking about trans* issues

./grep_comments.pl "$1" '(?i)\b((?!=transportation|transmission|transcript|translat|transparen)trans\S*|cis|cisgender)\b' | less
