#!/usr/bin/perl

# TODO:   Create this script.
#
# At a high level, it should:
#
#       1. extract all links within a person's comments 
#                   (ie. links to external websites, made by the person, not generated by Reddit)
#
#       2. optionally, try to identify domains that might be associated with that person
#
#
#
# To accomplish the second item, use this:
# 
#       https://en.wikipedia.org/wiki/Public_Suffix_List
#               
# by way of one of these modules:
#
#       Mozilla::PublicSuffix
#       Domain::PublicSuffix
#       ParseUtil::Domain
#
#
#
# It could even have some specialized code to identify users at specific websites.  I'm particularly
# curious if it can identify parts of websites I control, for example:
#
#           https://github.com/DeeNewcum/

die "This script is not yet implemented.\n";
